default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: insta_todo_development

test:
  <<: *default
  database: insta_todo_test

production:
  <<: *default
  database: insta_todo_production
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>
