default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: insta_todos_development

test:
  <<: *default
  database: insta_todos_test
