default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: insta_todo_development

test:
  <<: *default
  database: insta_todo_test
