# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b40cf33510eeb71eb6afc836c7c20936af4839ba19ee6cfea070fab41f5bb39b03ab595dad2a4d2a862ce42a408ecad56ab27505415d08a6e3e2efd9b67d9869

test:
  secret_key_base: 463788ee15b783348dc7b1860afeb9f70794a85e9eda2ddfb21cb400855f96203c1fe514f742756ee9a29b7def1b3483a4a3ca86535d615027fea68be07c99c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  database:
    username: ''
    password: ''
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
